export const PRIVACY_POLICY_LAST_UPDATED = 'June 17, 2026';

export const PRIVACY_POLICY = `Privacy Policy
Physiq: Macro Tracker
Last Updated: June 17, 2026

Physiq: Macro Tracker ("Physiq", "we", "our", or "us") respects your privacy and is committed to protecting your personal information. This Privacy Policy explains how information is collected, used, and protected when you use the Physiq: Macro Tracker mobile application and related services.

By using the app, you agree to the collection and use of information in accordance with this policy.

1. Information We Collect

Physiq is designed to minimize data collection. Most data remains stored locally on your device.

Information You Provide

The app may collect information you voluntarily provide, including:

Age
Height
Weight
Body fat percentage (optional)
Gender
Activity level
Fitness goal selections
Macro strategy selections
Dietary preferences or modifiers
Foods entered manually
Foods scanned via barcode

This information is used only to calculate macro targets and track nutrition.

2. Automatically Collected Information

Some limited technical information may be collected automatically to operate the app and improve functionality:

Device type
Operating system version
App version
Anonymous usage analytics
Crash reports

This data does not personally identify you.

3. Food Database and Barcode Scanning

Physiq may retrieve food nutrition information from external public food databases, including:

USDA FoodData Central
Open food databases used for barcode scanning

When you search for foods or scan barcodes:

The search query or barcode may be sent to these databases
Returned nutrition information is displayed in the app
The food may be saved locally on your device

No personal identifying information is transmitted during these requests.

4. Local Data Storage

Most data generated by the app is stored locally on your device, including:

Food logs
Saved foods
Macro targets
User preferences
Historical entries

If you delete the app, this data may be deleted unless you have backed up your device.

5. Apple Health (HealthKit)

If you choose to connect Apple Health on iPhone, Physiq may read the following data types from HealthKit, only after you grant permission through Apple's system prompt:

Active energy burned
Step count
Workout and exercise time
Heart rate and heart rate variability (SDNN)
Sleep analysis

This data is used solely on your device to adapt macro targets, hydration cues, and activity-aware fueling recommendations. Physiq does not write health data to Apple Health, does not use Health data for advertising or marketing, does not sell Health data, and does not share Health data with third parties.

Health-derived values are stored locally on your iPhone (for example, the latest activity summary used for target adjustments). You can revoke access at any time in the iPhone Settings app under Privacy & Security → Health → Physiq, or in the Apple Health app under your profile → Apps → Physiq.

The optional Apple Watch companion app displays macro and hydration summaries sent from your iPhone. It does not read HealthKit directly.

6. Advertising

If you use the free macro calculator on our website, advertisements may be displayed through advertising networks such as Google AdSense.

These services may use cookies or anonymous identifiers to provide relevant advertisements.

For more information, please review Google's privacy policy:
https://policies.google.com/privacy

The Physiq: Macro Tracker mobile app itself does not currently display third-party ads.

7. How We Use Information

Information collected through the app is used to:

Calculate personalized macro targets
Display nutrition information
Track food intake
Improve the accuracy of food search results
Improve app functionality
Diagnose crashes and technical issues

We do not sell your personal information.

8. Data Sharing

We do not sell, rent, or trade your personal information.

Limited information may be shared with service providers only when necessary to operate the app, such as:

Food database providers
Analytics services
Crash reporting services

These providers only receive the minimum information required to perform their services.

9. Data Security

We take reasonable measures to protect information stored by the app. However, no method of electronic storage or internet transmission is completely secure.

Users are responsible for securing their own devices.

10. Children's Privacy

Physiq: Macro Tracker is not intended for children under the age of 13.

We do not knowingly collect personal information from children under 13. If we become aware that such information has been collected, it will be deleted.

11. Health Disclaimer

Physiq: Macro Tracker provides nutrition calculations and informational tools only.

The app is not a medical device and is not intended to diagnose, treat, cure, or prevent any disease.

Always consult a qualified healthcare professional before making significant dietary or health changes.

12. Your Privacy Rights

Depending on your location, you may have rights to:

Access your data
Request deletion of your data
Request correction of inaccurate data

Because most data is stored locally on your device, you can delete your data by removing the app or clearing app storage.

13. Changes to This Policy

We may update this Privacy Policy from time to time.

Changes will be posted within the app or on the Physiq website with an updated revision date.

14. Contact

If you have questions about this Privacy Policy, you can contact us at:

Email: support@physiqmacros.com
Website: https://physiqmacros.com
`;
